version: '3.8'

networks:
    default:
        external: true
        name: spa_default

services:
    spa:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: spa
        image: raheeb/spa:latest
        volumes:
            - .:/var/www/html
        depends_on:
            - mysql
            - prometheus
            - mailpit


    mysql:
        image: mysql:8.0
        container_name: mysql
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - spa_mysql_data:/var/lib/mysql

    mysql-exporter:
        image: prom/mysqld-exporter
        container_name: mysql-exporter
        ports:
            - "9104:9104"
        environment:
            DATA_SOURCE_NAME: "root:pass123@(mysql:3306)/spa"
        command:
            - "--config.my-cnf=/etc/my.cnf"
        volumes:
            - ./monitoring/my.cnf:/etc/my.cnf


    prometheus:
        image: prom/prometheus
        container_name: prometheus
        ports:
            - "9090:9090"
        volumes:
            - ./monitoring:/etc/monitoring
            - ./monitoring/scrape_job.yml:/etc/monitoring/scrape_job.yml
        command:
            - --config.file=/etc/monitoring/scrape_job.yml
        depends_on:
            - mysql-exporter

    grafana:
        image: grafana/grafana
        container_name: grafana
        ports:
            - "3000:3000"
        depends_on:
            - prometheus


    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - '8000:8000'
        volumes:
            - .:/var/www/html
            - ./monitoring/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - spa

    mailpit:
        image: axllent/mailpit
        container_name: mailpit
        ports:
            - '1025:1025'
            - '8025:8025'

volumes:
    spa_mysql_data:
